language: python
python:
  - "3.6.5"
install:
  - pip install -r requirements.txt
script:
  - python -m compileall .
  - black --check `git ls-tree $(git branch | awk '/\*/ { print $2; }') -r --name-only | grep -E "py$"`
notifications:
email: false
